services:
  api:
    image: primsa-file-uploader
    container_name: prisma-file-uploader
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    depends_on:
      - postgres
    command: ["npm", "run", "dev"]

  postgres:
    image: postgres:14
    container_name: prisma-file-uploader-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
